"""80 — IAM Audit Tool engine. All audit logic lives here. Pages import from this file."""

import pandas as pd
from thefuzz import fuzz
import io, json, base64, re, random
from datetime import datetime, date, timedelta
import irs  # Handles the Identity Risk Scoring logic

# ─────────────────────────────────────────────────────────────────────────────
#  POLICY CONSTANTS  (sidebar overrides these at runtime)
# ─────────────────────────────────────────────────────────────────────────────
DORMANT_DAYS         = 90
PASSWORD_EXPIRY_DAYS = 90
FUZZY_THRESHOLD      = 88
MAX_SYSTEMS          = 3


# ─────────────────────────────────────────────────────────────────────────────
#  SEMANTIC INTELLIGENCE — department and access level normalisation
# ─────────────────────────────────────────────────────────────────────────────

DEPT_SYNONYMS = {
    "Finance": [
        "finance","finance department","finance dept","finance team",
        "finance division","finance function","finance group","finance unit",
        "finance & accounting","finance and accounting","finance/accounting",
        "financial","financial department","financial services",
        "financial management","financial operations","financial control",
        "financial controller","financial controllers","financial reporting",
        "financial planning","financial planning & analysis",
        "financial planning and analysis","fp&a","fpa",
        "accounting","accounting department","accounts","accounts department",
        "accounts team","accounts division","accountancy","accountants",
        "accounts & finance","accounts and finance","finance & accounts",
        "accounts payable","ap","accounts payable department","ap team",
        "accounts receivable","ar","accounts receivable department","ar team",
        "payroll","payroll department","payroll team","payroll & benefits",
        "payroll and benefits","salary","salaries","compensation",
        "compensation & benefits","compensation and benefits","c&b","cb",
        "total rewards","total reward","benefits","benefits administration",
        "treasury","treasury department","treasury management","treasury team",
        "treasury & cash management","cash management","liquidity management",
        "tax","taxation","tax department","tax team","indirect tax","direct tax",
        "vat","corporate tax","transfer pricing",
        "audit","internal audit","internal audit department","audit team",
        "finance audit","financial audit","external audit liaison",
        "management accounts","management accounting","cost accounting",
        "cost control","cost management","budgeting","budget","budgets",
        "planning","planning & budgeting","planning and budgeting",
        "forecasting","commercial finance","commercial","business finance",
        "group finance","central finance","group accounting",
        "shared services","shared services finance","finance shared services",
        "finance ops","finance operations","finance & operations",
        "billing","billing department","billing team","collections",
        "credit control","credit management","revenue","revenue accounting",
        "revenue recognition","statutory reporting","group reporting",
        "investor relations","finance business partner","finance bp",
        "gl","general ledger","fixed assets","asset management finance",
        "intercompany","reconciliation","financial risk","credit risk finance",
        "sap finance","oracle finance","netsuite","sage","xero","quickbooks",
        "dynamics finance","d365 finance",
    ],
    "IT": [
        "it","it department","it dept","it team","it division",
        "it function","it group","it services","it service",
        "information technology","information technology department",
        "information technology services","information technology division",
        "information systems","is","mis","management information systems",
        "technology","technology department","technology services",
        "technology team","technology division","technology group",
        "tech","tech team","tech department","tech services","tech division",
        "it operations","it ops","it operations & support","ito",
        "infrastructure","infrastructure & operations","i&o",
        "it infrastructure","infrastructure team","infrastructure department",
        "network","networking","network team","network & infrastructure",
        "network operations","noc","network operations centre",
        "systems","systems team","systems administration","sysadmin",
        "it support","support team","technical support","tech support",
        "helpdesk","help desk","service desk","it service desk","itsm",
        "end user computing","euc","desktop support","deskside support",
        "software development","software engineering","development",
        "it development","application development","app development",
        "software","software team","engineering","it engineering",
        "devops","dev ops","development operations","platform",
        "platform engineering","platform team","sre","site reliability",
        "site reliability engineering","cloud","cloud team","cloud services",
        "cloud operations","cloud & devops","cloud engineering",
        "backend","frontend","full stack","mobile development","mobile",
        "security","it security","information security","infosec",
        "cyber","cyber security","cybersecurity","it security team",
        "security operations","soc","security operations centre",
        "vulnerability management","penetration testing","pen test",
        "identity & access management","iam","identity management",
        "privileged access management","pam","endpoint security",
        "security engineering","security architecture","ciso office",
        "architecture","it architecture","enterprise architecture","ea",
        "solution architecture","technical architecture",
        "it strategy","digital strategy","technology strategy",
        "digital","digital team","digital services","digital transformation",
        "digital & technology","digital and technology","d&t","dt",
        "data engineering","data infrastructure","data platform",
        "bi","business intelligence","data warehouse","datawarehouse",
        "etl","data integration","reporting & analytics it",
        "it procurement","software licensing","asset management it",
        "it asset management","itam","change management it",
        "release management","it project management","it pmo",
        "vendor management it","it vendor management",
        "it governance","it compliance","it risk","grc it",
    ],
    "HR": [
        "hr","hr department","hr dept","hr team","hr division",
        "hr function","hr group","human resources","human resources department",
        "human resources team","human resources division",
        "human resource","human resource department",
        "people","people team","people department","people division",
        "people function","people & culture","people and culture",
        "people operations","people ops","people & organisation",
        "people and organisation","people & organizational development",
        "talent","talent team","talent management","talent acquisition",
        "talent & development","talent and development",
        "recruitment","recruitment team","recruitment department",
        "resourcing","resourcing team","talent resourcing",
        "staffing","staffing team","workforce","workforce planning",
        "headcount","headcount planning",
        "learning & development","learning and development","l&d","ld",
        "learning","learning team","training","training department",
        "training & development","training and development","t&d","td",
        "organisational development","organizational development","od",
        "organisation development","leadership development",
        "capability development","people development","talent development",
        "employee relations","er","employment relations",
        "employee experience","employee engagement","engagement",
        "culture","culture team","dei","diversity equity inclusion",
        "diversity & inclusion","diversity and inclusion","d&i",
        "wellbeing","employee wellbeing","wellness","health & wellbeing",
        "hr operations","hr ops","hris","hr information systems",
        "hrms","hr management systems","hr shared services",
        "people analytics","hr analytics","workforce analytics",
        "compensation & benefits","compensation and benefits","c&b","cb",
        "total rewards","total reward","benefits","benefits administration",
        "payroll","payroll team","payroll department",
        "hr business partner","hrbp","hr bp","business partner hr",
        "hr generalist","generalist hr",
        "hr compliance","employment law","er legal","hr legal",
        "immigration","visa","right to work",
    ],
    "Sales": [
        "sales","sales department","sales team","sales division",
        "sales function","sales group","sales & marketing",
        "sales and marketing","commercial","commercial team",
        "commercial department","commercial division",
        "business development","bd","biz dev","business dev",
        "inside sales","inside sales team","field sales","field sales team",
        "direct sales","indirect sales","outbound sales","inbound sales",
        "telesales","telephone sales","digital sales","online sales",
        "e-commerce sales","ecommerce sales",
        "enterprise sales","enterprise team","mid-market sales",
        "smb sales","small business sales","corporate sales",
        "strategic sales","national accounts","national sales",
        "regional sales","regional team","territory sales",
        "international sales","global sales","export sales",
        "account management","account managers","key accounts",
        "key account management","strategic accounts","named accounts",
        "global accounts","major accounts","national accounts",
        "revenue","revenue team","revenue operations","revops","rev ops",
        "go to market","gtm","growth","growth team",
        "new business","new business development","new logo",
        "channel","channel sales","channel team","channel management",
        "partner","partners","partnerships","alliance","alliances",
        "partner management","channel & alliances",
        "reseller","resellers","distributor","distribution",
        "pre-sales","presales","pre sales","solution consulting",
        "sales engineering","sales engineers","technical sales",
        "solutions","solutions team",
    ],
    "Marketing": [
        "marketing","marketing department","marketing team","marketing division",
        "marketing function","marketing group","marketing & comms",
        "marketing and communications","marketing & communications",
        "brand","brand team","brand marketing","brand management",
        "brand & marketing","branding","brand & comms",
        "digital marketing","digital marketing team","online marketing",
        "performance marketing","growth marketing","d2c marketing",
        "paid media","paid search","ppc","sem","seo","organic search",
        "social media","social media marketing","social","community",
        "community management","influencer","influencer marketing",
        "affiliate","affiliate marketing","programmatic","display advertising",
        "content","content team","content marketing","content strategy",
        "creative","creative team","creative services","design",
        "graphic design","brand design","marketing design",
        "copywriting","copy","editorial","publications",
        "video","video production","studio","production",
        "communications","comms","corporate communications","corp comms",
        "pr","public relations","media relations","press","press office",
        "external communications","internal communications",
        "investor communications","stakeholder communications",
        "events","events team","event management","conferences",
        "experiential","field marketing",
        "product marketing","pmm","product marketing management",
        "go to market marketing","gtm marketing","launch",
        "demand generation","demand gen","lead generation","lead gen",
        "campaigns","campaign management","campaign team",
        "marketing operations","marketing ops","mops","marops",
        "crm marketing","lifecycle marketing","retention marketing",
        "email marketing","marketing automation",
    ],
    "Operations": [
        "operations","ops","operations department","operations team",
        "operations division","business operations","biz ops","bizops",
        "operational","operational excellence","ops excellence",
        "supply chain","supply chain management","scm","supply chain team",
        "supply chain & operations","procurement & operations",
        "demand planning","supply planning","inventory","inventory management",
        "stock management","materials management","materials",
        "logistics","logistics team","logistics department","logistics & ops",
        "logistics & operations","logistics and operations",
        "distribution","distribution centre","dc","warehouse",
        "warehousing","warehouse operations","fulfillment","fulfilment",
        "dispatch","shipping","transport","transportation","fleet",
        "fleet management","fleet operations","last mile","delivery",
        "manufacturing","manufacturing operations","production","production team",
        "production operations","assembly","assembly operations","plant",
        "plant operations","factory","factory operations","workshop",
        "fabrication","process engineering","manufacturing engineering",
        "quality","quality assurance","qa","quality control","qc",
        "quality management","quality operations","testing","test",
        "quality & safety","hseq","health safety environment quality",
        "facilities","facilities management","facilities team","fm",
        "property","property management","real estate","estates",
        "building management","office management","workplace",
        "workplace services","workspace","environment","site management",
        "continuous improvement","ci","lean","lean operations","six sigma",
        "process improvement","process excellence","transformation",
        "operational transformation","business transformation","change",
        "field operations","field ops","field services","field service",
        "field engineering","installation","maintenance","technical operations",
    ],
    "Procurement": [
        "procurement","procurement department","procurement team",
        "procurement division","procurement function","procurement group",
        "purchasing","purchasing department","purchasing team","buying",
        "buying team","buyers","commercial procurement",
        "sourcing","strategic sourcing","sourcing team","sourcing & procurement",
        "category management","category","categories","category team",
        "indirect procurement","direct procurement","global procurement",
        "supply management","supplier management","vendor management",
        "supply base management","third party management","tpm",
        "contracts","contracts management","contract management",
        "contract administration","commercial contracts",
        "procurement & contracts","procurement and contracts",
        "p2p","procure to pay","purchase to pay","p2p team",
        "invoice processing","purchase orders","po management",
        "spend management","spend analysis","spend analytics",
        "cost reduction","savings","procurement savings",
        "logistics procurement","it procurement","capex procurement",
        "facilities procurement","services procurement",
    ],
    "Legal": [
        "legal","legal department","legal team","legal division",
        "legal function","legal group","legal services","legal & compliance",
        "legal and compliance","general counsel","gc","office of general counsel",
        "ogc","legal counsel","in-house legal","corporate legal",
        "contracts","contract management","commercial contracts legal",
        "company secretarial","company secretary","secretarial","cosec",
        "corporate secretarial","board secretariat","governance secretarial",
        "corporate law","corporate affairs","corporate governance",
        "litigation","dispute resolution","employment law","labour law",
        "intellectual property","ip","ip management","ip team",
        "trademarks","patents","copyright","licensing legal",
        "privacy","data privacy","data protection legal","gdpr legal",
        "regulatory","regulatory affairs","regulatory team","regulatory legal",
        "regulatory compliance legal","competition law","antitrust",
        "mergers & acquisitions","m&a","deal team","corporate transactions",
        "legal ops","legal operations","legal technology","legal tech",
        "commercial legal","legal commercial","real estate legal",
        "property legal","planning","planning legal",
    ],
    "Risk & Compliance": [
        "risk","risk management","risk department","risk team",
        "risk division","risk function","risk & compliance",
        "risk and compliance","enterprise risk","enterprise risk management",
        "erm","operational risk","operational risk management","orm",
        "credit risk","market risk","liquidity risk","financial risk management",
        "model risk","technology risk","cyber risk","third party risk",
        "vendor risk","supply chain risk","strategic risk",
        "compliance","compliance department","compliance team",
        "compliance division","compliance function","regulatory compliance",
        "compliance & risk","compliance and risk","compliance management",
        "grc","governance risk compliance","governance risk and compliance",
        "governance, risk and compliance","governance risk & compliance",
        "governance","governance team","corporate governance",
        "internal controls","controls","controls team","sox",
        "sox compliance","sox controls","j-sox","financial controls",
        "internal audit","internal audit department","internal audit team",
        "ia","group internal audit","audit & risk","audit and risk",
        "assurance","internal assurance","risk & assurance",
        "risk and assurance","combined assurance",
        "aml","anti money laundering","financial crime","fraud",
        "fraud prevention","fraud risk","fraud & financial crime",
        "kyc","know your customer","sanctions","financial intelligence",
        "counter fraud","economic crime",
        "regulatory affairs","regulatory","regulatory risk",
        "conduct risk","compliance monitoring","compliance testing",
        "data protection","dpo office","privacy","ciso",
        "information risk","information governance",
    ],
    "Support": [
        "support","customer support","customer service","client services",
        "client support","customer care","customer relations",
        "customer experience","cx","customer experience team",
        "contact centre","contact center","call centre","call center",
        "customer contact","customer operations","customer ops",
        "technical support","tech support","helpdesk","help desk",
        "it helpdesk","service desk","it service desk","1st line support",
        "2nd line support","3rd line support","first line","second line",
        "third line","l1","l2","l3","level 1","level 2","level 3",
        "customer success","cs","customer success team",
        "customer success management","csm","client success",
        "account management support","post-sales",
        "onboarding","customer onboarding","client onboarding",
        "implementation","implementations","professional services",
        "ps","customer implementation","solution implementation",
        "after sales","after-sales","aftersales","field service support",
        "warranty","returns","repairs","service centre","service center",
        "complaints","complaints handling","dispute resolution support",
        "escalations","customer escalations",
    ],
    "Engineering": [
        "engineering","software engineering","software development",
        "development","r&d","research and development","research & development",
        "technology engineering","tech engineering","it engineering",
        "backend","backend engineering","backend development",
        "frontend","frontend engineering","frontend development",
        "full stack","full stack engineering","full stack development",
        "mobile","mobile engineering","mobile development","ios","android",
        "qa engineering","test engineering","quality engineering","sdet",
        "data engineering","data platform engineering",
        "ml engineering","machine learning engineering","ai engineering",
        "platform","platform engineering","infrastructure engineering",
        "devops","devsecops","sre","site reliability engineering",
        "cloud engineering","cloud native","solutions engineering",
        "integration","integration engineering","api","api development",
        "architecture","software architecture","technical architecture",
        "embedded","embedded systems","hardware engineering","firmware",
        "iot","internet of things engineering",
    ],
    "Product": [
        "product","product management","product team","product department",
        "product division","product group","product & engineering",
        "product and engineering","product & design","product and design",
        "product & ux","product & technology","product strategy",
        "product operations","product ops","product development",
        "ux","user experience","ui","user interface","ux/ui","ui/ux",
        "design","design team","product design","experience design",
        "service design","interaction design","visual design",
        "product owner","product owners","business analysis","ba",
        "business analyst","business analysts","requirements",
        "digital product","digital product management",
    ],
    "Data & Analytics": [
        "data","data team","data department","data division",
        "data & analytics","data and analytics","analytics",
        "analytics team","analytics department","business analytics",
        "business intelligence","bi","bi team","reporting",
        "reporting & analytics","data science","data scientists",
        "data engineering","data platform","data infrastructure",
        "data management","data governance","data quality",
        "data strategy","chief data office","cdo office",
        "insights","insights team","customer insights","market insights",
        "consumer insights","research","market research",
        "advanced analytics","predictive analytics","ml","machine learning",
        "ai","artificial intelligence","ai & ml","decision science",
        "decision intelligence","applied science","quantitative",
    ],
    "Executive": [
        "executive","c-suite","c suite","leadership","senior leadership",
        "executive leadership","executive team","exec team","exec",
        "board","board of directors","directors","senior management",
        "management","management team","senior management team","smt",
        "managing directors","executive directors","group executive",
        "ceo office","ceo's office","president","president office",
        "chairman","chairman office","group","group management",
        "corporate","corporate office","headquarters","hq",
        "c-level","c level","office of the ceo","office of the cfo",
        "group leadership","global leadership","global management",
    ],
    "Customer Success": [
        "customer success","cs department","customer success team",
        "customer success management","client success","account success",
        "partner success","customer growth","customer retention",
        "renewal","renewals","renewal management","expansion",
        "upsell","cross-sell","post-sales success",
    ],
    "Project Management": [
        "project management","pmo","project management office",
        "programme management","program management","portfolio management",
        "project office","project delivery","delivery","delivery management",
        "project team","project managers","programme office",
        "change delivery","transformation delivery","it pmo",
    ],
    "Admin": [
        "admin","administration","administrative","administration department",
        "administrative services","office administration","office management",
        "pa","personal assistant","executive assistant","ea",
        "business support","business support services","admin & support",
        "corporate services","company administration","reception",
        "secretarial","office services","general administration",
    ],
    "Research": [
        "research","r&d","research and development","research & development",
        "innovation","innovation team","innovation lab","lab","laboratories",
        "scientific","science","clinical","clinical research","clinical trials",
        "regulatory affairs research","medical affairs","medical",
        "drug development","product research","market research research",
    ],
}

# ─────────────────────────────────────────────────────────────────────────────
#  ACCESS LEVEL SYNONYMS — maps every known variation to canonical form
# ─────────────────────────────────────────────────────────────────────────────
ACCESS_SYNONYMS = {
    "Admin": [
        "admin","administrator","administration access","system admin",
        "sysadmin","sys admin","system administrator","it admin",
        "local admin","domain admin","global admin","full admin",
        "super admin","superadmin","super administrator",
        "admin access","administrative access","administrative rights",
        "admin rights","admin privileges","administrative privileges",
        "root","root access","superuser","super user","su",
        "elevated","elevated access","elevated privileges",
        "privileged","privileged access","privileged user",
        "fullcontrol","full control","full access","all access",
        "unrestricted","unrestricted access","complete access",
        "all permissions","all rights","everything",
        "owner","resource owner","object owner",
        "global administrator","tenant admin","org admin",
        "enterprise admin","azure admin","aws admin",
        "cloud admin","platform admin","infrastructure admin",
        "application admin","app admin","system owner",
    ],
    "DBAdmin": [
        "dbadmin","dba","db admin","database admin","database administrator",
        "database administration","sql admin","sql server admin",
        "oracle dba","oracle admin","postgres admin","postgresql admin",
        "mysql admin","mongodb admin","db owner","database owner",
        "schema owner","schema admin","data admin","data administrator",
        "warehouse admin","datawarehouse admin","db2 admin","sybase admin",
        "nosql admin","redis admin","elasticsearch admin","database access",
    ],
    "Finance": [
        "finance","finance access","financial","financial access",
        "accounts","accounting","accounting access","accounts access",
        "payroll","payroll access","payment","payments","payment access",
        "general ledger","gl","gl access","ap access","ar access",
        "purchase ledger","sales ledger","erp finance","sap","sap finance",
        "sap access","oracle financials","oracle finance","netsuite",
        "sage","xero","quickbooks","dynamics finance","d365",
        "billing","billing access","invoicing","invoice access",
        "collections","treasury access","budgeting access",
    ],
    "HR": [
        "hr","hr access","human resources access","hris","hrms",
        "hris access","hrms access","workday","workday access",
        "oracle hr","sap hr","successfactors","bamboo hr","bamboohr",
        "people system","people access","payroll hr","recruitment access",
        "talent system","ats","applicant tracking","learning system",
        "lms access","performance system","hr portal",
    ],
    "ReadOnly": [
        "readonly","read only","read-only","read","view","view only",
        "view access","read access","viewer","viewers","observer",
        "monitor","monitoring","reporting","report","reports",
        "read & view","read and view","enquiry","enquiry only",
        "query only","query","browse","browse only","lookup",
        "lookup only","basic","basic access","standard read",
        "limited","limited access","restricted","restricted access",
        "no write","no edit","consume","consume only",
        "auditor","auditor access","audit read","compliance read",
    ],
    "Full Access": [
        "full access","full","complete","complete access",
        "unrestricted","all features","all functionality",
        "power user","advanced","advanced access","super user access",
    ]
}

# ─────────────────────────────────────────────────────────────────────────────
#  EXCEL GENERATION LOGIC
# ─────────────────────────────────────────────────────────────────────────────

def to_excel_bytes(findings_df, hr_df, sys_df, scope_start, scope_end, excluded_count, meta, opinion_text):
    """
    Generates the Excel download. Updated to include Sheet 10.
    """
    output = io.BytesIO()
    
    # 1. COMPUTE SCORES: Use irs.py to calculate risk scores before export
    # This attaches identity_risk_score and risk_band to the findings_df
    findings_df = irs.compute_irs(findings_df, scope_end)
    
    with pd.ExcelWriter(output, engine='xlsxwriter') as writer:
        # Note: You will need to add your logic for Sheets 1-9 back here.
        # This snippet ensures Sheet 10 is correctly generated.
        
        # ─────────────────────────────────────────────────────────────────
        # NEW: SHEET 10 - IDENTITY RISK REGISTER
        # ─────────────────────────────────────────────────────────────────
        # 2. BUILD REGISTER: Get the ranked dataframe for Sheet 10
        risk_register = irs.build_risk_register(findings_df)
        
        if not risk_register.empty:
            # Write to Excel
            risk_register.to_excel(writer, sheet_name="10. Identity Risk Register", index=False)
            
            # 3. FORMATTING: Apply risk band highlighting
            workbook  = writer.book
            worksheet = writer.sheets["10. Identity Risk Register"]
            
            # Setup colors based on risk bands
            fmt_critical = workbook.add_format({'bg_color': '#FFC7CE', 'font_color': '#9C0006'})
            fmt_high     = workbook.add_format({'bg_color': '#FFEB9C', 'font_color': '#9C5700'})
            
            # Apply formatting to the Risk_Band column (D)
            worksheet.conditional_format(1, 3, len(risk_register), 3, {
                'type':     'cell',
                'criteria': 'equal to',
                'value':    '"CRITICAL"',
                'format':   fmt_critical
            })
            worksheet.conditional_format(1, 3, len(risk_register), 3, {
                'type':     'cell',
                'criteria': 'equal to',
                'value':    '"HIGH"',
                'format':   fmt_high
            })

    return output.getvalue()
